In [1]:
# Use scipy.stats.describe()
import scipy.stats
import numpy as np

x = np.array ([[[34.0, 35.0, 39.0, 43.0, 46.5], [12,34,20.4, 32, 45], [30.5, 48.5, 50.0, 51.5, 52.5]]])
x.shape
# moments = scipy.stats.describe(x)
# moments.mean

# moments.variance

# moments.skewness

# moments.kurtosis


(1, 3, 5)

In [81]:
import numpy as np
mu = np.zeros(3,)
sigma = np.array([
    [2, 0, 1],
    [0, 2, -1],
    [1, -1, 2]
])
data = np.random.multivariate_normal(mu, sigma, size=(20,))
data
type(data)

array([[-1.19521128, -1.12855692,  1.03354531],
       [-1.32571612,  1.16986957, -1.65568434],
       [-1.55918587,  0.30122135,  0.00627913],
       [-0.18415155,  0.41579068, -0.95489154],
       [ 0.80695055,  0.18167647, -0.68629314],
       [ 0.47768436, -1.41271104,  1.04067876],
       [ 0.72972478, -0.39139704, -0.02450723],
       [-2.15048499, -1.88964128,  0.94996191],
       [ 3.37922992, -0.39555499,  4.11613703],
       [-3.951885  , -0.29622088, -1.25787336],
       [-0.91352029, -0.0507562 , -1.17949198],
       [ 1.39684294, -0.61346032,  2.11321904],
       [-3.12194674, -0.24679016, -0.96465357],
       [-0.5635005 , -2.46736133, -0.07549539],
       [-0.55997978,  0.16208027,  1.72984198],
       [ 0.31644048, -1.57761289,  0.97747686],
       [-0.8070699 , -0.61744692,  0.5797345 ],
       [-0.34539034, -0.30862272,  0.37257595],
       [ 0.27240404, -0.22994852,  0.3553838 ],
       [ 2.82842034, -0.39319589,  2.81819332]])

numpy.ndarray

In [83]:
data[0]

array([-1.19521128, -1.12855692,  1.03354531])

In [87]:
ts = np.array([[-0.19164118,  1.00407747, -0.02360305],
       [-0.01936799,  1.01121305, -0.05831341],
       [-0.06218145,  1.04689093, -0.09024696],
       [ 0.07747197,  1.07747197, -0.17910549],
       [ 0.04281346,  0.96534149, -0.11385   ],
       [ 0.03873598,  0.96534149, -0.19854329],
       [-0.10601427,  1.08562691, -0.15550245],
       [-0.19571865,  0.96941896, -0.058313]])

type(ts)

ts[0]


numpy.ndarray

array([-0.19164118,  1.00407747, -0.02360305])

In [82]:
from PyMoments import kstat

first_order_kstats = [
    kstat(data, (0,)),  # mean of column 0 
    kstat(data, (1,)),
    kstat(data, (2,))
]

sample_means = np.mean(data, axis=0)

print('First-order k-statistics:', first_order_kstats)
print('Sample means:', sample_means) 

First-order k-statistics: [-0.3235172475629343, -0.4894319383884626, 0.4647068517728036]
Sample means: [-0.32351725 -0.48943194  0.46470685]


In [ ]:
stat_array = []
for i in train_data: 
    lst = i

    lt = DataFrame.to_numpy(lst)

    first_order_kstats = [
        kstat(lt, (0,)),  # mean of column 0 
        kstat(lt, (1,)),
        kstat(lt, (2,))
    ]
    stat_array.extend(first_order_kstats)
stat_array = np.array(stat_array)
stat_array
type(stat_array)


In [4]:
second_order_kstats = np.zeros((3, 3))
for i in range(3):
    for j in range(3):
        second_order_kstats[i, j] = kstat(data, (i, j))

print('Second-order k-statistics:')
print(second_order_kstats)
print('Covariance matrix:')
print(np.cov(data.T))

Second-order k-statistics:
[[ 1.92406807 -0.13777227  1.2081332 ]
 [-0.13777227  3.1505376  -1.85292487]
 [ 1.2081332  -1.85292487  3.19490681]]
Covariance matrix:
[[ 1.92406807 -0.13777227  1.2081332 ]
 [-0.13777227  3.1505376  -1.85292487]
 [ 1.2081332  -1.85292487  3.19490681]]


In [5]:
print('Sample third-order k-statistics:') 
print(kstat(data, (0, 1, 2)))
print(kstat(data, (0, 0, 1)))
print(kstat(data, (2, 2, 2)))

Sample third-order k-statistics:
1.1629488516478432
1.7731889876060223
-2.4653554936195436


In [80]:
new_data = np.random.randn(5, 1)

print('First univariate k-stat:')
print(kstat(new_data, (0,)))

print('Second univariate k-stat:')
print(kstat(new_data, (0, 0)))

print('Third univariate k-stat:')
print(kstat(new_data, (0, 0, 0)))

print('Fourth univariate k-stat:')
print(kstat(new_data, (0, 0, 0, 0)))

First univariate k-stat:
-0.6221228094565847
Second univariate k-stat:
2.3428242784545192
Third univariate k-stat:
1.0270596975587007
Fourth univariate k-stat:
-11.778581078000077


In [77]:
#kstat(, (0,) * 9)
#dt = np.random.randn(10, 1)
dt = np.array([[1,2,4,5,6,3,5,2,6]])
dt
len(dt)
type(dt)
kstat(dt, (0,))
kstat(dt, (0,) * 1)
kstat(dt, (0,) * 2)
kstat(dt, (0,) * 3)
kstat(dt, (0,) * 4)
kstat(dt, (0,) * 5)

array([[1, 2, 4, 5, 6, 3, 5, 2, 6]])

1

numpy.ndarray

1.0

1.0

ZeroDivisionError: float division by zero

In [16]:
ls = (0,)
ls * 9

(0, 0, 0, 0, 0, 0, 0, 0, 0)

In [75]:
import numpy
#type(x,y,z): numpy.ndarray
x = numpy.array([[12,3,5,95,7]])
y = numpy.array([[45,2,10,6,9]])
z = numpy.array([[36,25,13,0,9]])

first_order = []
statis_array = []

for i in [x,y,z]:
    first_order.append(kstat(i, (0,)))
    first_order.append(kstat(i, (0,) * 1))
    #statis_array.extend(first_order)

first_order


[12.0, 12.0, 45.0, 45.0, 36.0, 36.0]

In [74]:
lst = [1, 2, 3]
lt = [1, 2, 3]

new_new = []
type(lst)

for i in [lst,lt]: 
    new_new.extend(i)

new_new = np.array(new_new)
new_new
type(new_new)

list

array([1, 2, 3, 1, 2, 3])

numpy.ndarray

In [47]:
(0,) * 2

ft = np.zeros(5)
type(ft)

ft[0:2]

(0, 0)

numpy.ndarray

array([0., 0.])

In [91]:
x = [2]
x.extend([0]*6)
x

[2, 0, 0, 0, 0, 0, 0]

In [107]:
# second-order k-statistics

test = train_data[0]

ts = DataFrame.to_numpy(test)

new = [1,2,3,4]

second_order_kstats = np.zeros((3, 3))
for i in range(3):
    for j in range(3):
        second_order_kstats[i, j] = kstat(ts, (i, j))
second_order_kstats

for i in range(3):
    for j in range(3):
        new.append(second_order_kstats[i][j])

new = np.array(new)
new

type(second_order_kstats)
second_order_kstats

array([ 0.00848515, -0.0001514 , -0.0016855 ,  0.00848515, -0.0001514 ,
       -0.0016855 ,  0.00848515, -0.0001514 , -0.0016855 ])

numpy.ndarray